{"abstract":[{"type":"text","text":":nodoc:"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"allResponseFields","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"] { get }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibanco"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"StripePayments"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"title":"allResponseFields","externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodMultibanco(py)allResponseFields"},"kind":"symbol","sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibanco\/allResponseFields"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodmultibanco\/allresponsefields"]},{"paths":["\/documentation\/stripepayments\/stppaymentmethodmultibanco\/allresponsefields"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibanco/allResponseFields":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibanco\/allResponseFields","type":"topic","kind":"symbol","title":"allResponseFields","role":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodmultibanco\/allresponsefields","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":":nodoc:"}],"navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodMultibanco":{"kind":"symbol","url":"\/documentation\/stripepayments\/stppaymentmethodmultibanco","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodMultibanco","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentMethodMultibanco","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodMultibanco"}],"title":"STPPaymentMethodMultibanco","abstract":[{"type":"text","text":"The Multibanco Payment Method."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"allResponseFields","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"allResponseFields"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:objc(cs)NSDictionary","text":"NSDictionary","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"allResponseFields"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibanco~1allResponseFields\/title","op":"replace","value":"allResponseFields"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibanco~1allResponseFields\/fragments","value":[{"text":"allResponseFields","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"STPPaymentMethodMultibanco","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibanco\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibanco\/fragments","value":[{"kind":"identifier","text":"STPPaymentMethodMultibanco"}]},{"value":[{"kind":"identifier","text":"STPPaymentMethodMultibanco"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodMultibanco\/navigatorTitle","op":"replace"}]}]}
