{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"RawRepresentable.init(rawValue:)","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/init(rawValue:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","role":"symbol","externalID":"s:14StripePayments23STPSourceRedirectStatusO8rawValueACSgSi_tcfc","roleHeading":"Initializer","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"},{"kind":"text","text":")"}],"modules":[{"name":"StripePayments"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceredirectstatus\/init(rawvalue:)"]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus/init(rawValue:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus\/init(rawValue:)","title":"init(rawValue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol","type":"topic","abstract":[],"url":"\/documentation\/stripepayments\/stpsourceredirectstatus\/init(rawvalue:)","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirectStatus":{"url":"\/documentation\/stripepayments\/stpsourceredirectstatus","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceRedirectStatus","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirectStatus","navigatorTitle":[{"text":"STPSourceRedirectStatus","kind":"identifier"}],"abstract":[{"text":"Redirect status types for a Source.","type":"text"}],"title":"STPSourceRedirectStatus","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/title","value":"STPSourceRedirectStatus","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceRedirectStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSourceRedirectStatus"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirectStatus\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
