{"metadata":{"title":"checks","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"checks"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardChecks","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardChecks"},{"kind":"text","text":"?"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentMethodCard(py)checks","roleHeading":"Instance Property","symbolKind":"property","modules":[{"name":"StripePayments"}],"role":"symbol","navigatorTitle":[{"text":"checks","kind":"identifier"}]},"abstract":[{"text":"Checks on Card address and CVC if provided.","type":"text"}],"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checks"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardChecks","text":"STPPaymentMethodCardChecks","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks","kind":"typeIdentifier"},{"kind":"text","text":"? { get }"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/checks"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/checks"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stppaymentmethodcard\/checks"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodCard","kind":"identifier"}],"title":"STPPaymentMethodCard","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPPaymentMethodCard"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard","abstract":[{"type":"text","text":"Contains details about a user’s credit card."}],"url":"\/documentation\/stripepayments\/stppaymentmethodcard"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCard/checks":{"navigatorTitle":[{"kind":"identifier","text":"checks"}],"url":"\/documentation\/stripepayments\/stppaymentmethodcard\/checks","title":"checks","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCard\/checks","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"checks"},{"text":": ","kind":"text"},{"text":"STPPaymentMethodCardChecks","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardChecks","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","abstract":[{"type":"text","text":"Checks on Card address and CVC if provided."}],"type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentMethodCardChecks":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPPaymentMethodCardChecks","kind":"identifier"}],"navigatorTitle":[{"text":"STPPaymentMethodCardChecks","kind":"identifier"}],"type":"topic","title":"STPPaymentMethodCardChecks","url":"\/documentation\/stripepayments\/stppaymentmethodcardchecks","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks","abstract":[{"text":"Checks on Card address and CVC.","type":"text"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"checks","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"checks","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentMethodCardChecks","kind":"typeIdentifier","text":"STPPaymentMethodCardChecks","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethodCardChecks"},{"kind":"text","text":" * "},{"kind":"identifier","text":"checks"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"STPPaymentMethodCard","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCard"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard\/navigatorTitle","value":[{"text":"STPPaymentMethodCard","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1checks\/title","value":"checks","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCard~1checks\/fragments","value":[{"text":"checks","kind":"identifier"}]},{"value":"STPPaymentMethodCardChecks","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/title"},{"op":"replace","value":[{"kind":"identifier","text":"STPPaymentMethodCardChecks"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentMethodCardChecks\/navigatorTitle","op":"replace","value":[{"text":"STPPaymentMethodCardChecks","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
