{"kind":"symbol","abstract":[{"text":"The keyboard appearance for the field.","type":"text"},{"type":"text","text":" "},{"text":"Default is ","type":"text"},{"code":".default","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"formKeyboardAppearance","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIKeyboardAppearance","preciseIdentifier":"c:@E@UIKeyboardAppearance"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","modules":[{"name":"StripePaymentsUI"}],"symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formKeyboardAppearance"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIKeyboardAppearance","preciseIdentifier":"c:@E@UIKeyboardAppearance"}],"externalID":"c:@M@StripePaymentsUI@objc(cs)STPMultiFormTextField(py)formKeyboardAppearance","title":"formKeyboardAppearance","navigatorTitle":[{"kind":"identifier","text":"formKeyboardAppearance"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formKeyboardAppearance"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formkeyboardappearance"]},{"paths":["\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formkeyboardappearance"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsui","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField":{"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPMultiFormTextField"}],"title":"STPMultiFormTextField","url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField","abstract":[{"text":"STPMultiFormTextField is a lightweight UIView that wraps a collection of STPFormTextFields and can automatically move to the next form field when one is completed.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPMultiFormTextField","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPMultiFormTextField/formKeyboardAppearance":{"title":"formKeyboardAppearance","abstract":[{"type":"text","text":"The keyboard appearance for the field."},{"type":"text","text":" "},{"text":"Default is ","type":"text"},{"type":"codeVoice","code":".default"},{"type":"text","text":"."}],"url":"\/documentation\/stripepaymentsui\/stpmultiformtextfield\/formkeyboardappearance","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"formKeyboardAppearance","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIKeyboardAppearance","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIKeyboardAppearance"}],"type":"topic","navigatorTitle":[{"text":"formKeyboardAppearance","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPMultiFormTextField\/formKeyboardAppearance","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"formKeyboardAppearance","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"formKeyboardAppearance","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@UIKeyboardAppearance","text":"UIKeyboardAppearance","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"formKeyboardAppearance"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/title","value":"STPMultiFormTextField"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/fragments","value":[{"kind":"identifier","text":"STPMultiFormTextField"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField\/navigatorTitle","value":[{"kind":"identifier","text":"STPMultiFormTextField"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formKeyboardAppearance\/title","value":"formKeyboardAppearance"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPMultiFormTextField~1formKeyboardAppearance\/fragments","value":[{"kind":"identifier","text":"formKeyboardAppearance"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
