{"abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"safariViewController"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"controller","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"kind":"text","text":", "},{"text":"initialLoadDidRedirectTo","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"URL"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":")"}]}]}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:initialLoadDidRedirectTo:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontroller(_:initialloaddidredirectto:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontroller(_:initialloaddidredirectto:)"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"safariViewController","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController","text":"SFSafariViewController"},{"text":", ","kind":"text"},{"text":"initialLoadDidRedirectTo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":")"}],"extendedModule":"StripePayments","symbolKind":"method","navigatorTitle":[{"text":"safariViewController:initialLoadDidRedirectToURL:","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","title":"safariViewController(_:initialLoadDidRedirectTo:)","roleHeading":"Instance Method","externalID":"c:@CM@StripePayments@objc(cs)STPRedirectContext(im)safariViewController:initialLoadDidRedirectToURL:"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/safariViewController(_:initialLoadDidRedirectTo:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/safariViewController(_:initialLoadDidRedirectTo:)","abstract":[{"type":"text","text":":nodoc:"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpredirectcontext\/safariviewcontroller(_:initialloaddidredirectto:)","type":"topic","role":"symbol","title":"safariViewController(_:initialLoadDidRedirectTo:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"safariViewController","kind":"identifier"},{"kind":"text","text":"("},{"text":"SFSafariViewController","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"initialLoadDidRedirectTo"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"safariViewController:initialLoadDidRedirectToURL:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}],"title":"STPRedirectContext","role":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","abstract":[{"type":"text","text":"This is a helper class for handling redirects associated with STPSource and"},{"text":" ","type":"text"},{"type":"text","text":"STPPaymentIntents."},{"text":" ","type":"text"},{"text":"Init and retain an instance with the Source or PaymentIntent you want to handle,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"type":"text","text":" "},{"text":"when the redirect completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"type":"text","text":" "},{"type":"text","text":"during this process, as all actions take place in either the Safari app"},{"text":" ","type":"text"},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"text":" ","type":"text"},{"text":"detect when the user has completed the necessary redirect action by listening","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for both app foregrounds and url callbacks received in the app delegate."},{"type":"text","text":" "},{"text":"However, it is possible the when the redirect is “completed”, the user may","type":"text"},{"type":"text","text":" "},{"text":"have not actually completed the necessary actions to authorize the charge.","type":"text"},{"text":" ","type":"text"},{"text":"You should not use either this class, nor ","type":"text"},{"type":"codeVoice","code":"STPAPIClient"},{"text":", as a way","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to determine when you should charge the Source or to determine if the redirect"},{"type":"text","text":" "},{"type":"text","text":"was successful. Use Stripe webhooks on your backend server to listen for Source"},{"type":"text","text":" "},{"text":"state changes and to make the charge.","type":"text"}],"url":"\/documentation\/stripepayments\/stpredirectcontext"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/SFSafariViewControllerDelegate-Implementations":{"type":"topic","url":"\/documentation\/stripepayments\/stpredirectcontext\/sfsafariviewcontrollerdelegate-implementations","abstract":[],"title":"SFSafariViewControllerDelegate Implementations","kind":"article","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/SFSafariViewControllerDelegate-Implementations","role":"collectionGroup"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"safariViewController:initialLoadDidRedirectToURL:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"safariViewController:initialLoadDidRedirectToURL:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"safariViewController:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SFSafariViewController","preciseIdentifier":"c:objc(cs)SFSafariViewController"},{"text":" *) ","kind":"text"},{"text":"controller","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"initialLoadDidRedirectToURL:"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"URL","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewController(_:initialLoadDidRedirectTo:)\/title","value":"safariViewController:initialLoadDidRedirectToURL:"},{"value":[{"text":"- ","kind":"text"},{"text":"safariViewController:initialLoadDidRedirectToURL:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1safariViewController(_:initialLoadDidRedirectTo:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title","value":"STPRedirectContext"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"text":"STPRedirectContext","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"STPRedirectContext"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}
