{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/stpredirectcontexterrordomain"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpredirectcontext\/stpredirectcontexterrordomain"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPRedirectContextErrorDomain","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The domain for NSErrors specific to "},{"type":"codeVoice","code":"STPRedirectContext"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/STPRedirectContextErrorDomain","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext"]]},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)STPRedirectContext(cpy)STPRedirectContextErrorDomain","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"STPRedirectContextErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextErrorDomain"}],"role":"symbol","title":"STPRedirectContextErrorDomain","roleHeading":"Type Property","symbolKind":"property"},"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext/STPRedirectContextErrorDomain":{"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext\/STPRedirectContextErrorDomain","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPRedirectContextErrorDomain"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"STPRedirectContextErrorDomain"}],"role":"symbol","title":"STPRedirectContextErrorDomain","url":"\/documentation\/stripepayments\/stpredirectcontext\/stpredirectcontexterrordomain","abstract":[{"text":"The domain for NSErrors specific to ","type":"text"},{"type":"codeVoice","code":"STPRedirectContext"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPRedirectContext":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPRedirectContext","kind":"identifier"}],"title":"STPRedirectContext","role":"symbol","navigatorTitle":[{"text":"STPRedirectContext","kind":"identifier"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPRedirectContext","abstract":[{"type":"text","text":"This is a helper class for handling redirects associated with STPSource and"},{"text":" ","type":"text"},{"type":"text","text":"STPPaymentIntents."},{"text":" ","type":"text"},{"text":"Init and retain an instance with the Source or PaymentIntent you want to handle,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"then choose a redirect method. The context will fire the completion handler"},{"type":"text","text":" "},{"text":"when the redirect completes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Due to the nature of iOS, very little concrete information can be gained"},{"type":"text","text":" "},{"type":"text","text":"during this process, as all actions take place in either the Safari app"},{"text":" ","type":"text"},{"type":"text","text":"or the sandboxed SFSafariViewController class. The context attempts to"},{"text":" ","type":"text"},{"text":"detect when the user has completed the necessary redirect action by listening","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for both app foregrounds and url callbacks received in the app delegate."},{"type":"text","text":" "},{"text":"However, it is possible the when the redirect is “completed”, the user may","type":"text"},{"type":"text","text":" "},{"text":"have not actually completed the necessary actions to authorize the charge.","type":"text"},{"text":" ","type":"text"},{"text":"You should not use either this class, nor ","type":"text"},{"type":"codeVoice","code":"STPAPIClient"},{"text":", as a way","type":"text"},{"type":"text","text":" "},{"type":"text","text":"to determine when you should charge the Source or to determine if the redirect"},{"type":"text","text":" "},{"type":"text","text":"was successful. Use Stripe webhooks on your backend server to listen for Source"},{"type":"text","text":" "},{"text":"state changes and to make the charge.","type":"text"}],"url":"\/documentation\/stripepayments\/stpredirectcontext"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"STPRedirectContextErrorDomain","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPRedirectContextErrorDomain","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"STPRedirectContextErrorDomain","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1STPRedirectContextErrorDomain\/title","op":"replace","value":"STPRedirectContextErrorDomain"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext~1STPRedirectContextErrorDomain\/fragments","op":"replace","value":[{"text":"STPRedirectContextErrorDomain","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/title","op":"replace","value":"STPRedirectContext"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/fragments","value":[{"kind":"identifier","text":"STPRedirectContext"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPRedirectContext\/navigatorTitle","value":[{"kind":"identifier","text":"STPRedirectContext"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
