{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpimagelibrary"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpimagelibrary"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI"]]},"abstract":[{"type":"text","text":"This class lets you access card icons used by the Stripe SDK. All icons are 32 x 20 points."}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/amexCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/applePayCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/cardBrandChoiceImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/cardBrandImage(for:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/cvcImage(for:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/dinersClubCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/discoverCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/errorImage(for:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/jcbCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/mastercardCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/templatedBrandImage(for:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/unionPayCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/unknownCardCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/visaCardImage()"],"title":"Type Methods"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPImageLibrary"}]}],"kind":"declarations"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments-ui\/SQ","doc:\/\/com.stripe.stripe-payments-ui\/SH"],"kind":"relationships"}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPImageLibrary","kind":"identifier"}],"symbolKind":"class","role":"symbol","roleHeading":"Class","title":"STPImageLibrary","externalID":"c:@M@StripePaymentsUI@objc(cs)STPImageLibrary","navigatorTitle":[{"text":"STPImageLibrary","kind":"identifier"}],"modules":[{"name":"StripePaymentsUI"}]},"sections":[],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsui","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/discoverCardImage()":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/discoverCardImage()","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/discovercardimage()","title":"discoverCardImage()","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"discoverCardImage"}],"abstract":[{"text":"An icon representing Discover.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"discoverCardImage","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/unionPayCardImage()":{"navigatorTitle":[{"kind":"identifier","text":"unionPayCardImage"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unionPayCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/unionPayCardImage()","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/unionpaycardimage()","abstract":[{"text":"An icon representing UnionPay.","type":"text"}],"title":"unionPayCardImage()"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/amexCardImage()":{"role":"symbol","kind":"symbol","title":"amexCardImage()","navigatorTitle":[{"kind":"identifier","text":"amexCardImage"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"amexCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/amexCardImage()","type":"topic","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/amexcardimage()","abstract":[{"text":"An icon representing American Express.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/templatedBrandImage(for:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/templatedBrandImage(for:)","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/templatedbrandimage(for:)","title":"templatedBrandImage(for:)","role":"symbol","navigatorTitle":[{"text":"templatedBrandImageForCardBrand:","kind":"identifier"}],"abstract":[{"text":"This returns the appropriate icon for the specified card brand as a","type":"text"},{"type":"text","text":" "},{"type":"text","text":"single color template that can be tinted"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"templatedBrandImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}]},"doc://com.stripe.stripe-payments-ui/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/unknownCardCardImage()":{"kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/unknowncardcardimage()","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/unknownCardCardImage()","title":"unknownCardCardImage()","role":"symbol","navigatorTitle":[{"text":"unknownCardCardImage","kind":"identifier"}],"abstract":[{"text":"An icon to use when the type of the card is unknown.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"unknownCardCardImage"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments-ui/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)NSObject","title":"NSObject"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/errorImage(for:)":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/errorImage(for:)","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/errorimage(for:)","title":"errorImage(for:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"errorImageForCardBrand:"}],"abstract":[{"text":"This returns a small icon indicating a card number error for the given card brand.","type":"text"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"errorImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPCardBrand","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/applePayCardImage()":{"role":"symbol","title":"applePayCardImage()","kind":"symbol","navigatorTitle":[{"text":"applePayCardImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"applePayCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/applePayCardImage()","type":"topic","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/applepaycardimage()","abstract":[{"type":"text","text":"An icon representing Apple Pay."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/cardBrandChoiceImage()":{"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/cardBrandChoiceImage()","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/cardbrandchoiceimage()","title":"cardBrandChoiceImage()","role":"symbol","navigatorTitle":[{"text":"cardBrandChoiceImage","kind":"identifier"}],"abstract":[{"type":"text","text":"This returns the icon for an unselected brand when multiple card brands are available."}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cardBrandChoiceImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/cardBrandImage(for:)":{"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/cardBrandImage(for:)","kind":"symbol","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/cardbrandimage(for:)","type":"topic","abstract":[{"text":"This returns the appropriate icon for the specified card brand.","type":"text"}],"title":"cardBrandImage(for:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cardBrandImage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"STPCardBrand","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand"},{"kind":"text","text":") -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"navigatorTitle":[{"kind":"identifier","text":"brandImageForCardBrand:"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/dinersClubCardImage()":{"role":"symbol","kind":"symbol","title":"dinersClubCardImage()","navigatorTitle":[{"text":"dinersClubCardImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dinersClubCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/dinersClubCardImage()","type":"topic","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/dinersclubcardimage()","abstract":[{"text":"An icon representing Diners Club.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/SQ"},"doc://com.stripe.stripe-payments-ui/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s23CustomStringConvertibleP"},"doc://com.stripe.stripe-payments-ui/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s7CVarArgP"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/cvcImage(for:)":{"abstract":[{"type":"text","text":"This returns a small icon indicating the CVC location for the given card brand."}],"url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/cvcimage(for:)","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/cvcImage(for:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cvcImageForCardBrand:"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cvcImage"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardBrand","text":"STPCardBrand"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"title":"cvcImage(for:)","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/mastercardCardImage()":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mastercardCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/mastercardCardImage()","title":"mastercardCardImage()","navigatorTitle":[{"kind":"identifier","text":"mastercardCardImage"}],"url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/mastercardcardimage()","abstract":[{"text":"An icon representing Mastercard.","type":"text"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/jcbCardImage()":{"title":"jcbCardImage()","abstract":[{"type":"text","text":"An icon representing JCB."}],"type":"topic","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/jcbcardimage()","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"jcbCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"navigatorTitle":[{"kind":"identifier","text":"jcbCardImage"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/jcbCardImage()","role":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/visaCardImage()":{"role":"symbol","title":"visaCardImage()","kind":"symbol","navigatorTitle":[{"text":"visaCardImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"visaCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/visaCardImage()","type":"topic","url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/visacardimage()","abstract":[{"type":"text","text":"An icon representing Visa."}]},"doc://com.stripe.stripe-payments-ui/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments-ui/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/objc(pl)NSObject"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/init":{"url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/init","type":"topic","title":"init","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/init","abstract":[],"role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"kind":"symbol"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary":{"abstract":[{"type":"text","text":"This class lets you access card icons used by the Stripe SDK. All icons are 32 x 20 points."}],"url":"\/documentation\/stripepaymentsui\/stpimagelibrary","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary","kind":"symbol","navigatorTitle":[{"text":"STPImageLibrary","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPImageLibrary"}],"title":"STPImageLibrary","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPImageLibrary","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPImageLibrary","kind":"identifier"}]},{"op":"replace","value":[{"text":"STPImageLibrary","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/init"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"},{"anchor":"Type-Methods","generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/amexCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/applePayCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/cardBrandChoiceImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/cardBrandImage(for:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/cvcImage(for:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/dinersClubCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/discoverCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/errorImage(for:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/jcbCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/mastercardCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/templatedBrandImage(for:)","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/unionPayCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/unknownCardCardImage()","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/visaCardImage()"],"title":"Type Methods"}],"path":"\/topicSections"},{"op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments-ui\/objc(cs)NSObject"],"title":"Inherits From"}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"STPImageLibrary","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1discoverCardImage()\/title","value":"discoverCardImage"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"text":"discoverCardImage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1discoverCardImage()\/fragments"},{"op":"replace","value":"unionPayCardImage","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1unionPayCardImage()\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"unionPayCardImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1unionPayCardImage()\/fragments"},{"value":"amexCardImage","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1amexCardImage()\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1amexCardImage()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"amexCardImage"}]},{"value":"templatedBrandImageForCardBrand:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1templatedBrandImage(for:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"templatedBrandImageForCardBrand:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1templatedBrandImage(for:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1unknownCardCardImage()\/title","value":"unknownCardCardImage"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1unknownCardCardImage()\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"unknownCardCardImage"}]},{"op":"replace","value":"errorImageForCardBrand:","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1errorImage(for:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1errorImage(for:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"errorImageForCardBrand:","kind":"identifier"}]},{"value":"applePayCardImage","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1applePayCardImage()\/title","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"applePayCardImage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1applePayCardImage()\/fragments"},{"value":"cardBrandChoiceImage","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1cardBrandChoiceImage()\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"cardBrandChoiceImage"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1cardBrandChoiceImage()\/fragments"},{"value":"brandImageForCardBrand:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1cardBrandImage(for:)\/title"},{"value":[{"kind":"text","text":"+ "},{"text":"brandImageForCardBrand:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1cardBrandImage(for:)\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1dinersClubCardImage()\/title","value":"dinersClubCardImage","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"dinersClubCardImage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1dinersClubCardImage()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1cvcImage(for:)\/title","value":"cvcImageForCardBrand:","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1cvcImage(for:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"cvcImageForCardBrand:"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1mastercardCardImage()\/title","value":"mastercardCardImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1mastercardCardImage()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"mastercardCardImage","kind":"identifier"}]},{"value":"jcbCardImage","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1jcbCardImage()\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1jcbCardImage()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"jcbCardImage","kind":"identifier"}],"op":"replace"},{"value":"visaCardImage","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1visaCardImage()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1visaCardImage()\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"visaCardImage"}]},{"op":"replace","value":"STPImageLibrary","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/fragments","value":[{"kind":"identifier","text":"STPImageLibrary"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/navigatorTitle","value":[{"text":"STPImageLibrary","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}
