{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/tax"},"metadata":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tax","kind":"identifier"}],"externalID":"c:@M@StripePayments@E@STPKlarnaLineItemType@STPKlarnaLineItemTypeTax","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItemTypeTax"}],"title":"STPKlarnaLineItemType.tax","roleHeading":"Case","symbolKind":"case","role":"symbol","modules":[{"name":"StripePayments"}]},"kind":"symbol","abstract":[{"type":"text","text":"The line item for taxes"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"tax"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype\/tax"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpklarnalineitemtype\/tax"]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType":{"type":"topic","abstract":[{"text":"The type of the Klarna line item.","type":"text"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPKlarnaLineItemType"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType","navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItemType"}],"url":"\/documentation\/stripepayments\/stpklarnalineitemtype","title":"STPKlarnaLineItemType","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPKlarnaLineItemType/tax":{"title":"STPKlarnaLineItemType.tax","type":"topic","url":"\/documentation\/stripepayments\/stpklarnalineitemtype\/tax","kind":"symbol","abstract":[{"text":"The line item for taxes","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"STPKlarnaLineItemTypeTax"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPKlarnaLineItemType\/tax","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"tax","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"STPKlarnaLineItemTypeTax"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPKlarnaLineItemTypeTax"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPKlarnaLineItemTypeTax","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/title","op":"replace","value":"STPKlarnaLineItemType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/fragments","value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType\/navigatorTitle","value":[{"text":"STPKlarnaLineItemType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1tax\/title","value":"STPKlarnaLineItemTypeTax"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPKlarnaLineItemType~1tax\/fragments","value":[{"text":"STPKlarnaLineItemTypeTax","kind":"identifier"}]}]}]}
