{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Private setter allows for setting the name of the app in the returnURL so","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"that it can be displayed on hooks.stripe.com if the automatic redirect back"},{"text":" ","type":"text"},{"text":"to the app fails.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"We intercept the reading of redirect dictionary from STPFormEncoder and replace"},{"text":" ","type":"text"},{"text":"the value of return_url if necessary","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirectDictionaryWithMerchantNameIfNecessary()","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsourceparams\/redirectdictionarywithmerchantnameifnecessary()"]},{"paths":["\/documentation\/stripepayments\/stpsourceparams\/redirectdictionarywithmerchantnameifnecessary()"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","navigatorTitle":[{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"}],"roleHeading":"Instance Method","extendedModule":"StripePayments","symbolKind":"method","modules":[{"name":"StripePayments"}],"title":"redirectDictionaryWithMerchantNameIfNecessary()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"externalID":"c:@CM@StripePayments@objc(cs)STPSourceParams(im)redirectDictionaryWithMerchantNameIfNecessary"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams/redirectDictionaryWithMerchantNameIfNecessary()":{"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams\/redirectDictionaryWithMerchantNameIfNecessary()","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"},{"text":"() -> [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]"}],"abstract":[{"text":"Private setter allows for setting the name of the app in the returnURL so","type":"text"},{"type":"text","text":" "},{"text":"that it can be displayed on hooks.stripe.com if the automatic redirect back","type":"text"},{"text":" ","type":"text"},{"text":"to the app fails.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"We intercept the reading of redirect dictionary from STPFormEncoder and replace"},{"type":"text","text":" "},{"text":"the value of return_url if necessary","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceparams\/redirectdictionarywithmerchantnameifnecessary()","title":"redirectDictionaryWithMerchantNameIfNecessary()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceParams":{"abstract":[{"type":"text","text":"An object representing parameters used to create a Source object."}],"url":"\/documentation\/stripepayments\/stpsourceparams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceParams","type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPSourceParams"}],"title":"STPSourceParams","role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSourceParams"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"redirectDictionaryWithMerchantNameIfNecessary"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"NSDictionary","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1redirectDictionaryWithMerchantNameIfNecessary()\/title","value":"redirectDictionaryWithMerchantNameIfNecessary"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams~1redirectDictionaryWithMerchantNameIfNecessary()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"redirectDictionaryWithMerchantNameIfNecessary","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/title","value":"STPSourceParams"},{"value":[{"kind":"identifier","text":"STPSourceParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/fragments","op":"replace"},{"value":[{"text":"STPSourceParams","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceParams\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}
