{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"tosShownAndAccepted","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"wasAccepted","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"company"},{"kind":"text","text":": "},{"text":"STPConnectAccountCompanyParams","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"wasAccepted","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Must be YES, but only if the user was shown & accepted the ToS"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Information about the company or business. See "},{"type":"codeVoice","code":"STPConnectAccountCompanyParams"},{"text":".","type":"text"}]}],"name":"company"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/init(tosshownandaccepted:company:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpconnectaccountparams\/init(tosshownandaccepted:company:)"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"Initialize "},{"type":"codeVoice","code":"STPConnectAccountParams"},{"type":"text","text":" with tosShownAndAccepted = YES"},{"text":" ","type":"text"},{"text":"This method cannot be called with ","type":"text"},{"code":"wasAccepted == NO","type":"codeVoice"},{"text":", guarded by a ","type":"text"},{"type":"codeVoice","code":"NSParameterAssert()"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"Use this init method if you want to set the ","type":"text"},{"code":"tosShownAndAccepted","type":"codeVoice"},{"type":"text","text":" parameter. If you"},{"type":"text","text":" "},{"type":"text","text":"don’t, use the "},{"type":"codeVoice","code":"initWithCompany:"},{"text":" version instead.","type":"text"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:company:)","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Initializer","symbolKind":"init","navigatorTitle":[{"kind":"identifier","text":"initWithTosShownAndAccepted:company:"}],"role":"symbol","modules":[{"name":"StripePayments"}],"title":"init(tosShownAndAccepted:company:)","externalID":"c:@M@StripePayments@objc(cs)STPConnectAccountParams(im)initWithTosShownAndAccepted:company:","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"tosShownAndAccepted","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"company","kind":"externalParam"},{"kind":"text","text":": "},{"text":"STPConnectAccountCompanyParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountCompanyParams":{"navigatorTitle":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconnectaccountcompanyparams","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","title":"STPConnectAccountCompanyParams","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPConnectAccountCompanyParams","kind":"identifier"}],"abstract":[{"text":"Information about the company or business to use with ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountParams"},{"text":".","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPConnectAccountParams"}],"abstract":[{"type":"text","text":"Parameters for creating a Connect Account token."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams","title":"STPConnectAccountParams","url":"\/documentation\/stripepayments\/stpconnectaccountparams","navigatorTitle":[{"kind":"identifier","text":"STPConnectAccountParams"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConnectAccountParams/init(tosShownAndAccepted:company:)":{"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithTosShownAndAccepted:company:"}],"url":"\/documentation\/stripepayments\/stpconnectaccountparams\/init(tosshownandaccepted:company:)","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountParams\/init(tosShownAndAccepted:company:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"tosShownAndAccepted","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"company","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"STPConnectAccountCompanyParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","title":"init(tosShownAndAccepted:company:)","abstract":[{"text":"Initialize ","type":"text"},{"code":"STPConnectAccountParams","type":"codeVoice"},{"type":"text","text":" with tosShownAndAccepted = YES"},{"type":"text","text":" "},{"type":"text","text":"This method cannot be called with "},{"type":"codeVoice","code":"wasAccepted == NO"},{"type":"text","text":", guarded by a "},{"code":"NSParameterAssert()","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Use this init method if you want to set the "},{"type":"codeVoice","code":"tosShownAndAccepted"},{"type":"text","text":" parameter. If you"},{"text":" ","type":"text"},{"type":"text","text":"don’t, use the "},{"code":"initWithCompany:","type":"codeVoice"},{"type":"text","text":" version instead."}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"initWithTosShownAndAccepted:company:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithTosShownAndAccepted:company:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithTosShownAndAccepted:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"text":"wasAccepted","kind":"internalParam"},{"kind":"text","text":" "},{"text":"company:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConnectAccountCompanyParams","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPConnectAccountCompanyParams","kind":"typeIdentifier","text":"STPConnectAccountCompanyParams"},{"text":" *) ","kind":"text"},{"text":"company","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"name":"wasAccepted","content":[{"type":"paragraph","inlineContent":[{"text":"Must be YES, but only if the user was shown & accepted the ToS","type":"text"}]}]},{"name":"company","content":[{"inlineContent":[{"text":"Information about the company or business. See ","type":"text"},{"type":"codeVoice","code":"STPConnectAccountCompanyParams"},{"type":"text","text":"."}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":"STPConnectAccountCompanyParams","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/fragments","op":"replace","value":[{"text":"STPConnectAccountCompanyParams","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPConnectAccountCompanyParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountCompanyParams\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/title","op":"replace","value":"STPConnectAccountParams"},{"value":[{"kind":"identifier","text":"STPConnectAccountParams"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams\/navigatorTitle","value":[{"text":"STPConnectAccountParams","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(tosShownAndAccepted:company:)\/title","op":"replace","value":"initWithTosShownAndAccepted:company:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConnectAccountParams~1init(tosShownAndAccepted:company:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithTosShownAndAccepted:company:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
