{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"topicSections":[{"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/decodedObject(fromAPIResponse:)"],"title":"Type Methods","generated":true}],"metadata":{"roleHeading":"API Collection","title":"STPAPIResponseDecodable Implementations","role":"collectionGroup","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/STPAPIResponseDecodable-Implementations","interfaceLanguage":"swift"},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/stpapiresponsedecodable-implementations"]},{"paths":["\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/stpapiresponsedecodable-implementations"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode":{"abstract":[{"text":"Contains instructions for presenting the QR code required to complete a PayNow payment.","type":"text"},{"text":" ","type":"text"},{"text":"You cannot directly instantiate an ","type":"text"},{"type":"codeVoice","code":"STPIntentActionPayNowDisplayQrCode"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","title":"STPIntentActionPayNowDisplayQrCode","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPIntentActionPayNowDisplayQrCode"}],"role":"symbol","navigatorTitle":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPIntentActionPayNowDisplayQrCode/decodedObject(fromAPIResponse:)":{"abstract":[{"text":"Parses an response from the Stripe API (in JSON format; represented as","type":"text"},{"type":"text","text":" "},{"text":"an ","type":"text"},{"type":"codeVoice","code":"NSDictionary"},{"text":") into an instance of the class.","type":"text"}],"kind":"symbol","title":"decodedObject(fromAPIResponse:)","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodedObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"fromAPIResponse"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier","text":"AnyHashable"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?) -> `Self`","kind":"text"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/decodedObject(fromAPIResponse:)","url":"\/documentation\/stripepayments\/stpintentactionpaynowdisplayqrcode\/decodedobject(fromapiresponse:)","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/topicSections","value":[{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPIntentActionPayNowDisplayQrCode\/decodedObject(fromAPIResponse:)"]}],"op":"replace"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":"STPIntentActionPayNowDisplayQrCode","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/fragments","value":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"op":"replace"},{"value":[{"text":"STPIntentActionPayNowDisplayQrCode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1decodedObject(fromAPIResponse:)\/title","value":"decodedObjectFromAPIResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPIntentActionPayNowDisplayQrCode~1decodedObject(fromAPIResponse:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
