{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidRequest","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/invalidrequest"]},{"paths":["\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/invalidrequest"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeInvalidRequest"}],"role":"symbol","title":"STPSetupIntentLastSetupErrorType.invalidRequest","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidRequest"}],"symbolKind":"case","externalID":"c:@M@StripePayments@E@STPSetupIntentLastSetupErrorType@STPSetupIntentLastSetupErrorTypeInvalidRequest","modules":[{"name":"StripePayments"}]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/invalidRequest","interfaceLanguage":"swift"},"abstract":[{"text":"Invalid request errors.  Typically, this is because your request has invalid parameters.","type":"text"}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType/invalidRequest":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidRequest","kind":"identifier"}],"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorTypeInvalidRequest","kind":"identifier"}],"kind":"symbol","title":"STPSetupIntentLastSetupErrorType.invalidRequest","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType\/invalidRequest","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype\/invalidrequest","abstract":[{"type":"text","text":"Invalid request errors.  Typically, this is because your request has invalid parameters."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSetupIntentLastSetupErrorType":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The type of the error represented by "},{"code":"STPSetupIntentLastSetupError","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Some STPSetupIntentLastError properties are only populated for certain error types."}],"navigatorTitle":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSetupIntentLastSetupErrorType","title":"STPSetupIntentLastSetupErrorType","url":"\/documentation\/stripepayments\/stpsetupintentlastsetuperrortype"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"STPSetupIntentLastSetupErrorTypeInvalidRequest"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeInvalidRequest"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPSetupIntentLastSetupErrorTypeInvalidRequest","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1invalidRequest\/title","value":"STPSetupIntentLastSetupErrorTypeInvalidRequest","op":"replace"},{"value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorTypeInvalidRequest"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType~1invalidRequest\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/title","op":"replace","value":"STPSetupIntentLastSetupErrorType"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/fragments","value":[{"text":"STPSetupIntentLastSetupErrorType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSetupIntentLastSetupErrorType\/navigatorTitle","value":[{"kind":"identifier","text":"STPSetupIntentLastSetupErrorType"}],"op":"replace"}]}]}
