{"sections":[],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"UITextViewDelegate.textView(_:shouldInteractWith:in:interaction:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/textview(_:shouldinteractwith:in:interaction:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/textview(_:shouldinteractwith:in:interaction:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/textView(_:shouldInteractWith:in:interaction:)"},"metadata":{"symbolKind":"method","title":"textView(_:shouldInteractWith:in:interaction:)","role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@StripePaymentsUI@objc(cs)STPAUBECSDebitFormView(im)textView:shouldInteractWithURL:inRange:interaction:","navigatorTitle":[{"text":"textView:shouldInteractWithURL:inRange:interaction:","kind":"identifier"}],"modules":[{"name":"StripePaymentsUI"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textView","kind":"identifier"},{"kind":"text","text":"("},{"text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldInteractWith"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier","text":"NSRange"},{"text":", ","kind":"text"},{"text":"interaction","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextItemInteraction","text":"UITextItemInteraction"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"textView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"textView","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UITextView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UITextView"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldInteractWith"},{"kind":"text","text":" "},{"text":"URL","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"characterRange"},{"text":": ","kind":"text"},{"text":"NSRange","preciseIdentifier":"c:@T@NSRange","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"interaction"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@UITextItemInteraction","text":"UITextItemInteraction","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView/textView(_:shouldInteractWith:in:interaction:)":{"kind":"symbol","abstract":[],"title":"textView(_:shouldInteractWith:in:interaction:)","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView\/textView(_:shouldInteractWith:in:interaction:)","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview\/textview(_:shouldinteractwith:in:interaction:)","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"textView:shouldInteractWithURL:inRange:interaction:"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"textView"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UITextView","text":"UITextView","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldInteractWith"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRange"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"interaction"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@UITextItemInteraction","text":"UITextItemInteraction","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPAUBECSDebitFormView":{"abstract":[{"text":"STPAUBECSDebitFormView is a subclass of UIControl that contains all of the necessary fields and legal text for collecting AU BECS Debit payments.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For additional customization options - seealso: STPFormTextFieldContainer"}],"kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPAUBECSDebitFormView","type":"topic","role":"symbol","title":"STPAUBECSDebitFormView","url":"\/documentation\/stripepaymentsui\/stpaubecsdebitformview","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPAUBECSDebitFormView"}],"navigatorTitle":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsui","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"textView:shouldInteractWithURL:inRange:interaction:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"textView:shouldInteractWithURL:inRange:interaction:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"textView:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITextView","preciseIdentifier":"c:objc(cs)UITextView"},{"kind":"text","text":" *) "},{"text":"textView","kind":"internalParam"},{"kind":"text","text":" "},{"text":"shouldInteractWithURL:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"URL","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"inRange:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSRange","kind":"typeIdentifier","preciseIdentifier":"c:@S@_NSRange"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"characterRange"},{"text":" ","kind":"text"},{"text":"interaction:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@UITextItemInteraction","text":"UITextItemInteraction"},{"text":") ","kind":"text"},{"text":"interaction","kind":"internalParam"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1textView(_:shouldInteractWith:in:interaction:)\/title","value":"textView:shouldInteractWithURL:inRange:interaction:"},{"value":[{"kind":"text","text":"- "},{"text":"textView:shouldInteractWithURL:inRange:interaction:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView~1textView(_:shouldInteractWith:in:interaction:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/title","value":"STPAUBECSDebitFormView","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/fragments","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"STPAUBECSDebitFormView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPAUBECSDebitFormView\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}
