{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"LinkConsumerIncentive","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}],"kind":"symbol","topicSections":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/LinkConsumerIncentive\/allResponseFields"]},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/LinkConsumerIncentive\/decodedObjectFromAPIResponse:"],"generated":true,"title":"Type Methods","anchor":"Type-Methods"}],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/LinkConsumerIncentive","interfaceLanguage":"occ"},"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/linkconsumerincentive"]}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"]}],"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"externalID":"c:@M@StripePayments@objc(cs)LinkConsumerIncentive","roleHeading":"Class","fragments":[{"kind":"identifier","text":"LinkConsumerIncentive"}],"role":"symbol","navigatorTitle":[{"text":"LinkConsumerIncentive","kind":"identifier"}],"title":"LinkConsumerIncentive","symbolKind":"class","modules":[{"name":"StripePayments"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/LinkConsumerIncentive":{"role":"symbol","title":"LinkConsumerIncentive","kind":"symbol","abstract":[],"fragments":[{"text":"LinkConsumerIncentive","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/LinkConsumerIncentive","url":"\/documentation\/stripepayments\/linkconsumerincentive","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"title":"STPAPIResponseDecodable","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/LinkConsumerIncentive/decodedObjectFromAPIResponse:":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/LinkConsumerIncentive\/decodedObjectFromAPIResponse:","abstract":[],"type":"topic","role":"symbol","kind":"symbol","title":"decodedObjectFromAPIResponse:","url":"\/documentation\/stripepayments\/linkconsumerincentive\/decodedobjectfromapiresponse:","fragments":[{"kind":"text","text":"+ "},{"text":"decodedObjectFromAPIResponse:","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"decodedObjectFromAPIResponse:"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/LinkConsumerIncentive/allResponseFields":{"title":"allResponseFields","type":"topic","role":"symbol","kind":"symbol","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/LinkConsumerIncentive\/allResponseFields","fragments":[{"text":"allResponseFields","kind":"identifier"}],"url":"\/documentation\/stripepayments\/linkconsumerincentive\/allresponsefields"},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"}},"variantOverrides":[{"patch":[{"op":"replace","value":"STPAPIResponseDecodable","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
