{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpcollectbankaccounterror"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpcollectbankaccounterror"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Error codes generated by STPBankAccountCollector","type":"text"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/financialConnectionsSDKNotLinked","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/invalidClientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/unexpectedError"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/init(rawValue:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/CustomStringConvertible-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/Equatable-Implementations","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"kind":"symbol","identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError","interfaceLanguage":"swift"},"relationshipsSections":[{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH","doc:\/\/com.stripe.stripe-payments\/SY"],"title":"Conforms To"}],"metadata":{"title":"STPCollectBankAccountError","modules":[{"name":"StripePayments"}],"externalID":"c:@M@StripePayments@E@STPCollectBankAccountError","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCollectBankAccountError","kind":"identifier"}],"symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountError"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPCollectBankAccountError","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError":{"abstract":[{"text":"Error codes generated by STPBankAccountCollector","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPCollectBankAccountError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCollectBankAccountError","kind":"identifier"}],"title":"STPCollectBankAccountError","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror","type":"topic"},"doc://com.stripe.stripe-payments/SQ":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/CustomStringConvertible-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/CustomStringConvertible-Implementations","title":"CustomStringConvertible Implementations","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/customstringconvertible-implementations","type":"topic","kind":"article","abstract":[],"role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/financialConnectionsSDKNotLinked":{"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"financialConnectionsSDKNotLinked"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/financialConnectionsSDKNotLinked","abstract":[{"text":"Error when using APIs that require the linking the StripeFinancialConnections SDK","type":"text"}],"title":"STPCollectBankAccountError.financialConnectionsSDKNotLinked","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/financialconnectionssdknotlinked","role":"symbol","navigatorTitle":[{"text":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/unexpectedError":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/unexpectedError","title":"STPCollectBankAccountError.unexpectedError","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/unexpectederror","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"unexpectedError","kind":"identifier"}],"abstract":[{"type":"text","text":"Unexpected behavior in calling the API"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPCollectBankAccountErrorUnexpectedError"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/Equatable-Implementations":{"kind":"article","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/Equatable-Implementations","role":"collectionGroup","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/equatable-implementations","title":"Equatable Implementations","abstract":[]},"doc://com.stripe.stripe-payments/s8CopyableP":{"type":"unresolvable","title":"Swift.Copyable","identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP"},"doc://com.stripe.stripe-payments/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.stripe.stripe-payments\/SY"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/RawRepresentable-Implementations","abstract":[],"title":"RawRepresentable Implementations","kind":"article","type":"topic","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/rawrepresentable-implementations","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/invalidClientSecret":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/invalidClientSecret","title":"STPCollectBankAccountError.invalidClientSecret","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/invalidclientsecret","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidClientSecret"}],"abstract":[{"type":"text","text":"Error when a secret can not be parsed to retrieve the ID"}],"role":"symbol","navigatorTitle":[{"text":"STPCollectBankAccountErrorInvalidClientSecret","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/SH":{"identifier":"doc:\/\/com.stripe.stripe-payments\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/init(rawValue:)":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/init(rawValue:)","title":"init(rawValue:)","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/init(rawvalue:)","type":"topic","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"role":"symbol"},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPCollectBankAccountError"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"STPCollectBankAccountError","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"STPCollectBankAccountError"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/financialConnectionsSDKNotLinked","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/invalidClientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/unexpectedError"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"STPCollectBankAccountError","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/title","value":"STPCollectBankAccountError","op":"replace"},{"op":"replace","value":[{"text":"STPCollectBankAccountError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/navigatorTitle","op":"replace","value":[{"text":"STPCollectBankAccountError","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1financialConnectionsSDKNotLinked\/title","value":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1financialConnectionsSDKNotLinked\/fragments","value":[{"text":"STPCollectBankAccountErrorFinancialConnectionsSDKNotLinked","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1unexpectedError\/title","value":"STPCollectBankAccountErrorUnexpectedError"},{"value":[{"text":"STPCollectBankAccountErrorUnexpectedError","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1unexpectedError\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1invalidClientSecret\/title","value":"STPCollectBankAccountErrorInvalidClientSecret"},{"op":"replace","value":[{"text":"STPCollectBankAccountErrorInvalidClientSecret","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1invalidClientSecret\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
