{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPPaymentIntent","kind":"identifier"}],"externalID":"c:@M@StripePayments@objc(cs)STPPaymentIntent","roleHeading":"Class","title":"STPPaymentIntent","symbolKind":"class","navigatorTitle":[{"kind":"identifier","text":"STPPaymentIntent"}],"modules":[{"name":"StripePayments"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent"},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/amount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/canceledAt","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/captureMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/confirmationMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/lastPaymentError","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/livemode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextSourceAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethodId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethodTypes","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/receiptEmail","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/setupFutureUsage","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/shipping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/sourceId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/stripeDescription","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/stripeId"],"anchor":"Instance-Properties","title":"Instance Properties"},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/STPAPIResponseDecodable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","doc:\/\/com.stripe.stripe-payments\/s7CVarArgP","doc:\/\/com.stripe.stripe-payments\/s8CopyableP","doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","doc:\/\/com.stripe.stripe-payments\/SQ","doc:\/\/com.stripe.stripe-payments\/SH"],"title":"Conforms To","type":"conformsTo"}],"abstract":[{"text":"A PaymentIntent tracks the process of collecting a payment from your customer.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stppaymentintent"]},{"paths":["\/documentation\/stripepayments\/stppaymentintent"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentIntent","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"overview","level":2,"text":"Overview","type":"heading"},{"style":"note","name":"See Also","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"Https:\/\/Stripe.Com\/Docs\/Api#Payment_intents","type":"text"}]}]},{"style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"https:\/\/stripe.com\/docs\/payments\/3d-secure"}],"type":"paragraph"}],"name":"See Also"}],"kind":"content"}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/stripeDescription":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"stripeDescription","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"stripeDescription"}],"title":"stripeDescription","role":"symbol","type":"topic","abstract":[{"text":"The ","type":"text"},{"code":"description","type":"codeVoice"},{"type":"text","text":" field of the PaymentIntent."},{"type":"text","text":" "},{"text":"An arbitrary string attached to the object. Often useful for displaying to users.","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintent\/stripedescription","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/stripeDescription","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/confirmationMethod":{"type":"topic","title":"confirmationMethod","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"confirmationMethod"}],"abstract":[{"type":"text","text":"Confirmation method of this PaymentIntent"}],"role":"symbol","url":"\/documentation\/stripepayments\/stppaymentintent\/confirmationmethod","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"confirmationMethod","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentConfirmationMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentConfirmationMethod"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/confirmationMethod"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/allResponseFields":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"allResponseFields"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/allResponseFields","abstract":[{"text":"The raw JSON response used to create the object. This can be useful for accessing","type":"text"},{"type":"text","text":" "},{"type":"text","text":"fields that haven’t yet been made into native properties in the SDK."}],"title":"allResponseFields","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"allResponseFields"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]","kind":"text"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintent\/allresponsefields"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/paymentMethodTypes":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethodTypes","url":"\/documentation\/stripepayments\/stppaymentintent\/paymentmethodtypes","type":"topic","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"paymentMethodTypes","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSNumber","kind":"typeIdentifier","text":"NSNumber"},{"text":"]","kind":"text"}],"kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The list of payment method types (e.g. "},{"code":"[NSNumber(value: STPPaymentMethodType.card.rawValue)]","type":"codeVoice"},{"type":"text","text":") that this PaymentIntent is allowed to use."}],"navigatorTitle":[{"text":"paymentMethodTypes","kind":"identifier"}],"title":"paymentMethodTypes"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/sourceId":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sourceId"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"sourceId","kind":"identifier"}],"title":"sourceId","role":"symbol","type":"topic","abstract":[{"type":"text","text":"The Stripe ID of the Source used in this PaymentIntent."}],"url":"\/documentation\/stripepayments\/stppaymentintent\/sourceid","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/sourceId","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/clientSecret":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"clientSecret"}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/clientSecret","abstract":[{"type":"text","text":"The client secret used to fetch this PaymentIntent"}],"title":"clientSecret","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clientSecret"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"type":"topic","url":"\/documentation\/stripepayments\/stppaymentintent\/clientsecret"},"doc://com.stripe.stripe-payments/objc(pl)NSObject":{"identifier":"doc:\/\/com.stripe.stripe-payments\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/s8CopyableP":{"identifier":"doc:\/\/com.stripe.stripe-payments\/s8CopyableP","type":"unresolvable","title":"Swift.Copyable"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/description":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"description"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"description"}],"title":"description","role":"symbol","type":"topic","abstract":[{"text":":nodoc:","type":"text"}],"url":"\/documentation\/stripepayments\/stppaymentintent\/description","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/description","kind":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/currency":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/currency","abstract":[{"type":"text","text":"The currency associated with the PaymentIntent."}],"type":"topic","role":"symbol","kind":"symbol","title":"currency","url":"\/documentation\/stripepayments\/stppaymentintent\/currency","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currency"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"navigatorTitle":[{"text":"currency","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/nextSourceAction":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"nextSourceAction","kind":"identifier"},{"text":": ","kind":"text"},{"text":"STPIntentAction","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction"},{"text":"?","kind":"text"}],"deprecated":false,"navigatorTitle":[{"kind":"identifier","text":"nextSourceAction"}],"kind":"symbol","title":"nextSourceAction","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextSourceAction","url":"\/documentation\/stripepayments\/stppaymentintent\/nextsourceaction","abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"status == STPPaymentIntentStatusRequiresAction"},{"text":", this","type":"text"},{"text":" ","type":"text"},{"text":"property contains the next source action to take for this PaymentIntent.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/setupFutureUsage":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/setupFutureUsage","abstract":[{"text":"When provided, this property indicates how you intend to use the payment method that your customer provides after the current payment completes. If applicable, additional authentication may be performed to comply with regional legislation or network rules required to enable the usage of the same payment method for additional payments.","type":"text"},{"text":" ","type":"text"},{"text":"Use on_session if you intend to only reuse the payment method when the customer is in your checkout flow. Use off_session if your customer may or may not be in your checkout flow.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"setupFutureUsage","url":"\/documentation\/stripepayments\/stppaymentintent\/setupfutureusage","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setupFutureUsage"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentSetupFutureUsage","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentSetupFutureUsage"}],"navigatorTitle":[{"text":"setupFutureUsage","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/paymentMethod":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"paymentMethod"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentMethod","text":"STPPaymentMethod"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"paymentMethod","kind":"identifier"}],"kind":"symbol","title":"paymentMethod","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethod","url":"\/documentation\/stripepayments\/stppaymentintent\/paymentmethod","abstract":[{"type":"text","text":"The optionally expanded PaymentMethod used in this PaymentIntent."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/receiptEmail":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/receiptEmail","abstract":[{"type":"text","text":"Email address that the receipt for the resulting payment will be sent to."}],"type":"topic","role":"symbol","kind":"symbol","title":"receiptEmail","url":"\/documentation\/stripepayments\/stppaymentintent\/receiptemail","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"receiptEmail"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"receiptEmail","kind":"identifier"}]},"doc://com.stripe.stripe-payments/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s28CustomDebugStringConvertibleP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPAPIResponseDecodable":{"abstract":[{"type":"text","text":"Objects conforming to STPAPIResponseDecodable can be automatically converted"},{"type":"text","text":" "},{"text":"from a JSON dictionary that was returned from the Stripe API.","type":"text"}],"url":"\/documentation\/stripepayments\/stpapiresponsedecodable","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable","type":"topic","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPAPIResponseDecodable","kind":"identifier"}],"title":"STPAPIResponseDecodable","navigatorTitle":[{"text":"STPAPIResponseDecodable","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/livemode":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"livemode","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"livemode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/livemode","url":"\/documentation\/stripepayments\/stppaymentintent\/livemode","title":"livemode","abstract":[{"type":"text","text":"Whether or not this PaymentIntent was created in livemode."}]},"doc://com.stripe.stripe-payments/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/created":{"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"created","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DateV","text":"Date"}],"navigatorTitle":[{"text":"created","kind":"identifier"}],"kind":"symbol","title":"created","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/created","url":"\/documentation\/stripepayments\/stppaymentintent\/created","abstract":[{"text":"When the PaymentIntent was created.","type":"text"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/amount":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/amount","abstract":[{"text":"Amount intended to be collected by this PaymentIntent.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"amount","url":"\/documentation\/stripepayments\/stppaymentintent\/amount","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"amount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"text":"amount","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/shipping":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shipping"},{"kind":"text","text":": "},{"text":"STPPaymentIntentShippingDetails","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentShippingDetails","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"shipping","kind":"identifier"}],"kind":"symbol","title":"shipping","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/shipping","url":"\/documentation\/stripepayments\/stppaymentintent\/shipping","abstract":[{"type":"text","text":"Shipping information for this PaymentIntent."}],"role":"symbol"},"doc://com.stripe.stripe-payments/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.stripe.stripe-payments\/s7CVarArgP"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent":{"title":"STPPaymentIntent","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent","role":"symbol","abstract":[{"type":"text","text":"A PaymentIntent tracks the process of collecting a payment from your customer."}],"navigatorTitle":[{"text":"STPPaymentIntent","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stppaymentintent","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPPaymentIntent","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/lastPaymentError":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lastPaymentError","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPPaymentIntentLastPaymentError","text":"STPPaymentIntentLastPaymentError"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"lastPaymentError"}],"kind":"symbol","title":"lastPaymentError","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/lastPaymentError","url":"\/documentation\/stripepayments\/stppaymentintent\/lastpaymenterror","abstract":[{"type":"text","text":"The payment error encountered in the previous PaymentIntent confirmation."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/stripeId":{"abstract":[{"type":"text","text":"The Stripe ID of the PaymentIntent."}],"role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/stripeId","url":"\/documentation\/stripepayments\/stppaymentintent\/stripeid","type":"topic","navigatorTitle":[{"text":"stripeId","kind":"identifier"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stripeId"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"kind":"symbol","title":"stripeId"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/canceledAt":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/canceledAt","abstract":[{"type":"text","text":"If status is "},{"type":"codeVoice","code":".canceled"},{"type":"text","text":", when the PaymentIntent was canceled."}],"type":"topic","role":"symbol","kind":"symbol","title":"canceledAt","url":"\/documentation\/stripepayments\/stppaymentintent\/canceledat","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"canceledAt","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DateV","text":"Date","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"canceledAt","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/paymentMethodId":{"fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"paymentMethodId","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"paymentMethodId","kind":"identifier"}],"kind":"symbol","title":"paymentMethodId","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethodId","url":"\/documentation\/stripepayments\/stppaymentintent\/paymentmethodid","abstract":[{"type":"text","text":"The Stripe ID of the PaymentMethod used in this PaymentIntent."}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/STPAPIResponseDecodable-Implementations":{"title":"STPAPIResponseDecodable Implementations","kind":"article","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/STPAPIResponseDecodable-Implementations","url":"\/documentation\/stripepayments\/stppaymentintent\/stpapiresponsedecodable-implementations","type":"topic","role":"collectionGroup"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/captureMethod":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/captureMethod","abstract":[{"type":"text","text":"Capture method of this PaymentIntent"}],"type":"topic","role":"symbol","kind":"symbol","title":"captureMethod","url":"\/documentation\/stripepayments\/stppaymentintent\/capturemethod","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"captureMethod"},{"text":": ","kind":"text"},{"text":"STPPaymentIntentCaptureMethod","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentCaptureMethod"}],"navigatorTitle":[{"text":"captureMethod","kind":"identifier"}]},"doc://com.stripe.stripe-payments/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.stripe.stripe-payments\/SH"},"doc://com.stripe.stripe-payments/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.stripe.stripe-payments\/SQ"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/status":{"fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"status"},{"kind":"text","text":": "},{"text":"STPPaymentIntentStatus","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPPaymentIntentStatus"}],"navigatorTitle":[{"text":"status","kind":"identifier"}],"kind":"symbol","title":"status","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/status","url":"\/documentation\/stripepayments\/stppaymentintent\/status","abstract":[{"type":"text","text":"Status of the PaymentIntent"}],"role":"symbol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPPaymentIntent/nextAction":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextAction","abstract":[{"type":"text","text":"If "},{"type":"codeVoice","code":"status == .requiresAction"},{"type":"text","text":", this"},{"type":"text","text":" "},{"text":"property contains the next action to take for this PaymentIntent.","type":"text"}],"type":"topic","role":"symbol","kind":"symbol","title":"nextAction","url":"\/documentation\/stripepayments\/stppaymentintent\/nextaction","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"nextAction"},{"kind":"text","text":": "},{"text":"STPIntentAction","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPIntentAction"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"nextAction"}]},"doc://com.stripe.stripe-payments/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.stripe.stripe-payments\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"STPPaymentIntent"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"STPPaymentIntent","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/allResponseFields","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/amount","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/canceledAt","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/captureMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/clientSecret","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/confirmationMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/created","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/currency","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/description","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/lastPaymentError","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/livemode","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/nextSourceAction","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethod","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethodId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/paymentMethodTypes","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/receiptEmail","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/setupFutureUsage","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/shipping","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/sourceId","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/status","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/stripeDescription","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/stripeId"],"generated":true},{"generated":true,"identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPPaymentIntent\/STPAPIResponseDecodable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations"}]},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.stripe.stripe-payments\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPAPIResponseDecodable"]}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPPaymentIntent"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1stripeDescription\/title","op":"replace","value":"stripeDescription"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1stripeDescription\/fragments","value":[{"text":"stripeDescription","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1confirmationMethod\/title","value":"confirmationMethod"},{"value":[{"text":"confirmationMethod","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1confirmationMethod\/fragments"},{"value":"allResponseFields","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1allResponseFields\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1allResponseFields\/fragments","value":[{"kind":"identifier","text":"allResponseFields"}]},{"op":"replace","value":"paymentMethodTypes","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1paymentMethodTypes\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1paymentMethodTypes\/fragments","value":[{"kind":"identifier","text":"paymentMethodTypes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1sourceId\/title","value":"sourceId","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1sourceId\/fragments","op":"replace","value":[{"text":"sourceId","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1clientSecret\/title","value":"clientSecret","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1clientSecret\/fragments","value":[{"text":"clientSecret","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1description\/title","value":"description","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1description\/fragments","value":[{"kind":"identifier","text":"description"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1currency\/title","value":"currency"},{"value":[{"kind":"identifier","text":"currency"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1currency\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1nextSourceAction\/title","op":"replace","value":"nextSourceAction"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1nextSourceAction\/fragments","value":[{"text":"nextSourceAction","kind":"identifier"}],"op":"replace"},{"value":"setupFutureUsage","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1setupFutureUsage\/title","op":"replace"},{"value":[{"kind":"identifier","text":"setupFutureUsage"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1setupFutureUsage\/fragments"},{"value":"paymentMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1paymentMethod\/title"},{"value":[{"kind":"identifier","text":"paymentMethod"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1paymentMethod\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1receiptEmail\/title","value":"receiptEmail","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1receiptEmail\/fragments","value":[{"kind":"identifier","text":"receiptEmail"}],"op":"replace"},{"value":"STPAPIResponseDecodable","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/title"},{"value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPAPIResponseDecodable\/navigatorTitle","value":[{"kind":"identifier","text":"STPAPIResponseDecodable"}]},{"value":"livemode","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1livemode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1livemode\/fragments","value":[{"kind":"identifier","text":"livemode"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1created\/title","op":"replace","value":"created"},{"value":[{"kind":"identifier","text":"created"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1created\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1amount\/title","value":"amount","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1amount\/fragments","value":[{"text":"amount","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1shipping\/title","value":"shipping","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1shipping\/fragments","value":[{"text":"shipping","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/title","value":"STPPaymentIntent"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/fragments","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPPaymentIntent"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1lastPaymentError\/title","value":"lastPaymentError","op":"replace"},{"value":[{"kind":"identifier","text":"lastPaymentError"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1lastPaymentError\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1stripeId\/title","op":"replace","value":"stripeId"},{"value":[{"text":"stripeId","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1stripeId\/fragments"},{"value":"canceledAt","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1canceledAt\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1canceledAt\/fragments","op":"replace","value":[{"kind":"identifier","text":"canceledAt"}]},{"op":"replace","value":"paymentMethodId","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1paymentMethodId\/title"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1paymentMethodId\/fragments","value":[{"text":"paymentMethodId","kind":"identifier"}],"op":"replace"},{"value":"captureMethod","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1captureMethod\/title"},{"value":[{"text":"captureMethod","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1captureMethod\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1status\/title","value":"status"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1status\/fragments","value":[{"text":"status","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1nextAction\/title","value":"nextAction"},{"value":[{"kind":"identifier","text":"nextAction"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPPaymentIntent~1nextAction\/fragments","op":"replace"}]}]}
