{"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The available payment sources the customer has (this may be an empty array)."}],"variants":[{"paths":["\/documentation\/stripepayments\/stpcustomer\/sources"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcustomer\/sources"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/sources"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer"]]},"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sources"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","text":"STPSourceProtocol"},{"text":"]","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"sources"}],"externalID":"c:@M@StripePayments@objc(cs)STPCustomer(py)sources","modules":[{"name":"StripePayments"}],"roleHeading":"Instance Property","title":"sources","symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"sources"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol","kind":"typeIdentifier","text":"STPSourceProtocol"},{"kind":"text","text":"] { get }"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceProtocol":{"role":"symbol","navigatorTitle":[{"text":"STPSourceProtocol","kind":"identifier"}],"abstract":[{"type":"text","text":"Objects conforming to this protocol can be attached to a Stripe Customer object"},{"text":" ","type":"text"},{"type":"text","text":"as a payment source."}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsourceprotocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"STPSourceProtocol","kind":"identifier"}],"title":"STPSourceProtocol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceProtocol"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer":{"url":"\/documentation\/stripepayments\/stpcustomer","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer","kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPCustomer","kind":"identifier"}],"title":"STPCustomer","abstract":[{"type":"text","text":"An "},{"code":"STPCustomer","type":"codeVoice"},{"type":"text","text":" represents a deserialized Customer object from the Stripe API."},{"type":"text","text":" "},{"text":"You shouldn’t need to instantiate an ","type":"text"},{"type":"codeVoice","code":"STPCustomer"},{"text":" – you should instead use","type":"text"},{"text":" ","type":"text"},{"code":"STPCustomerContext","type":"codeVoice"},{"text":" to manage retrieving and updating a customer.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPCustomer","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCustomer/sources":{"url":"\/documentation\/stripepayments\/stpcustomer\/sources","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCustomer\/sources","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sources"}],"title":"sources","abstract":[{"text":"The available payment sources the customer has (this may be an empty array).","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sources","kind":"identifier"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(pl)STPSourceProtocol","text":"STPSourceProtocol","kind":"typeIdentifier"},{"kind":"text","text":"]"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sources","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"sources"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<STPSourceProtocol>>","preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sources"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/title","value":"STPSourceProtocol","op":"replace"},{"op":"replace","value":[{"text":"STPSourceProtocol","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPSourceProtocol"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/title","op":"replace","value":"STPCustomer"},{"value":[{"kind":"identifier","text":"STPCustomer"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer\/navigatorTitle","value":[{"text":"STPCustomer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1sources\/title","value":"sources","op":"replace"},{"value":[{"text":"sources","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCustomer~1sources\/fragments","op":"replace"}]}]}
