{"kind":"symbol","variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/init"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"StripePayments"}],"navigatorTitle":[{"kind":"identifier","text":"init"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method","externalID":"c:@M@StripePayments@objc(cs)STPConfirmPaymentMethodOptions(im)init","title":"init","fragments":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions"]]},"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/init","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"init","kind":"identifier"},{"text":";","kind":"text"}]}]}],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions":{"title":"STPConfirmPaymentMethodOptions","abstract":[{"text":"Options to update the associated PaymentMethod during PaymentIntent confirmation.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions/init":{"navigatorTitle":[{"kind":"identifier","text":"init"}],"kind":"symbol","title":"init","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/init","type":"topic","abstract":[],"role":"symbol","fragments":[{"kind":"text","text":"- "},{"text":"init","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/init"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/title","value":"STPConfirmPaymentMethodOptions"},{"value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"STPConfirmPaymentMethodOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
