{"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/STPFormEncodable-Implementations"]]},"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called "},{"type":"codeVoice","code":"expMonth"},{"type":"text","text":", but the Stripe API expects a field called "},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"variants":[{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/propertynamestoformfieldnamesmapping()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/propertynamestoformfieldnamesmapping()"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"roleHeading":"Type Method","symbolKind":"method","extendedModule":"StripePayments","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"modules":[{"name":"StripePayments"}],"role":"symbol","title":"propertyNamesToFormFieldNamesMapping()","externalID":"c:@CM@StripePayments@objc(cs)STPConfirmPaymentMethodOptions(cm)propertyNamesToFormFieldNamesMapping","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"text":"() -> [","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"]"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/propertyNamesToFormFieldNamesMapping()"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions/propertyNamesToFormFieldNamesMapping()":{"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"text":"() -> [","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":" : ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]","kind":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/propertyNamesToFormFieldNamesMapping()","navigatorTitle":[{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/propertynamestoformfieldnamesmapping()","role":"symbol","kind":"symbol","abstract":[{"text":"This maps properties on an object that is being form-encoded into parameter names in the Stripe API. For example, STPCardParams has a field called ","type":"text"},{"code":"expMonth","type":"codeVoice"},{"type":"text","text":", but the Stripe API expects a field called "},{"type":"codeVoice","code":"exp_month"},{"type":"text","text":". This dictionary represents a mapping from the former to the latter (in other words, STPCardParams.propertyNamesToFormFieldNamesMapping()[“expMonth”] == “exp_month”.)"}],"title":"propertyNamesToFormFieldNamesMapping()"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions":{"title":"STPConfirmPaymentMethodOptions","abstract":[{"text":"Options to update the associated PaymentMethod during PaymentIntent confirmation.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"navigatorTitle":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions","role":"symbol","kind":"symbol","type":"topic","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPConfirmPaymentMethodOptions/STPFormEncodable-Implementations":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPConfirmPaymentMethodOptions\/STPFormEncodable-Implementations","url":"\/documentation\/stripepayments\/stpconfirmpaymentmethodoptions\/stpformencodable-implementations","role":"collectionGroup","title":"STPFormEncodable Implementations","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"propertyNamesToFormFieldNamesMapping"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"+ "},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"propertyNamesToFormFieldNamesMapping"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"propertyNamesToFormFieldNamesMapping","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1propertyNamesToFormFieldNamesMapping()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions~1propertyNamesToFormFieldNamesMapping()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"propertyNamesToFormFieldNamesMapping","kind":"identifier"}]},{"op":"replace","value":"STPConfirmPaymentMethodOptions","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/title"},{"value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPConfirmPaymentMethodOptions\/navigatorTitle","op":"replace","value":[{"text":"STPConfirmPaymentMethodOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
