{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@StripePayments@E@STPBankAccountStatus@STPBankAccountStatusVerified","modules":[{"name":"StripePayments"}],"roleHeading":"Case","role":"symbol","title":"STPBankAccountStatus.verified","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"verified","kind":"identifier"}],"symbolKind":"case","navigatorTitle":[{"text":"STPBankAccountStatusVerified","kind":"identifier"}]},"abstract":[{"type":"text","text":"Bank account verification has succeeded."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verified"},"variants":[{"paths":["\/documentation\/stripepayments\/stpbankaccountstatus\/verified"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpbankaccountstatus\/verified"]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"verified","kind":"identifier"}]}]}],"sections":[],"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus/verified":{"kind":"symbol","type":"topic","navigatorTitle":[{"text":"STPBankAccountStatusVerified","kind":"identifier"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"verified","kind":"identifier"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus\/verified","title":"STPBankAccountStatus.verified","abstract":[{"text":"Bank account verification has succeeded.","type":"text"}],"url":"\/documentation\/stripepayments\/stpbankaccountstatus\/verified"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPBankAccountStatus":{"navigatorTitle":[{"text":"STPBankAccountStatus","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPBankAccountStatus","abstract":[{"type":"text","text":"Possible validation states for a bank account."}],"url":"\/documentation\/stripepayments\/stpbankaccountstatus","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPBankAccountStatus"}],"title":"STPBankAccountStatus"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"STPBankAccountStatusVerified","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"STPBankAccountStatusVerified","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"STPBankAccountStatusVerified","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1verified\/title","value":"STPBankAccountStatusVerified"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus~1verified\/fragments","value":[{"kind":"identifier","text":"STPBankAccountStatusVerified"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/title","value":"STPBankAccountStatus","op":"replace"},{"op":"replace","value":[{"text":"STPBankAccountStatus","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPBankAccountStatus\/navigatorTitle","value":[{"text":"STPBankAccountStatus","kind":"identifier"}]}]}]}
