{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"redirect","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceRedirect","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect","text":"STPSourceRedirect","kind":"typeIdentifier"},{"text":"? { get }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"role":"symbol","title":"redirect","externalID":"c:@M@StripePayments@objc(cs)STPSource(py)redirect","modules":[{"name":"StripePayments"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"redirect","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceRedirect","text":"STPSourceRedirect"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"redirect","kind":"identifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","abstract":[{"type":"text","text":"Information related to the redirect flow. Present if the source’s flow"},{"type":"text","text":" "},{"text":"is redirect.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpsource\/redirect"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpsource\/redirect"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/redirect"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"]]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSourceRedirect":{"title":"STPSourceRedirect","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPSourceRedirect","kind":"identifier"}],"navigatorTitle":[{"text":"STPSourceRedirect","kind":"identifier"}],"url":"\/documentation\/stripepayments\/stpsourceredirect","abstract":[{"type":"text","text":"Information related to a source’s redirect flow."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect","kind":"symbol","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"STPSource"}],"abstract":[{"text":"Representation of a customer’s payment instrument created with the Stripe API. - seealso: https:\/\/stripe.com\/docs\/api#sources","type":"text"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpsource","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"STPSource","kind":"identifier"}],"title":"STPSource","type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPSource/redirect":{"abstract":[{"type":"text","text":"Information related to the redirect flow. Present if the source’s flow"},{"type":"text","text":" "},{"type":"text","text":"is redirect."}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSource\/redirect","role":"symbol","type":"topic","title":"redirect","kind":"symbol","url":"\/documentation\/stripepayments\/stpsource\/redirect","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"redirect"},{"kind":"text","text":": "},{"text":"STPSourceRedirect","preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceRedirect","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"redirect"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"redirect","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"redirect"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@M@StripePayments@objc(cs)STPSourceRedirect","kind":"typeIdentifier","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPSourceRedirect","text":"STPSourceRedirect"},{"text":" * ","kind":"text"},{"text":"redirect","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"STPSourceRedirect","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/title"},{"value":[{"kind":"identifier","text":"STPSourceRedirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSourceRedirect\/navigatorTitle","value":[{"kind":"identifier","text":"STPSourceRedirect"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/title","op":"replace","value":"STPSource"},{"value":[{"text":"STPSource","kind":"identifier"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"STPSource"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1redirect\/title","value":"redirect","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"redirect"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPSource~1redirect\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}
