{"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@M@StripePaymentsUI@objc(cs)STPImageLibrary(cm)mastercardCardImage","title":"mastercardCardImage()","modules":[{"name":"StripePaymentsUI"}],"roleHeading":"Type Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"mastercardCardImage","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mastercardCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"mastercardCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/mastercardCardImage()"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepaymentsui\/stpimagelibrary\/mastercardcardimage()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepaymentsui\/stpimagelibrary\/mastercardcardimage()"]}],"abstract":[{"text":"An icon representing Mastercard.","type":"text"}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary":{"abstract":[{"type":"text","text":"This class lets you access card icons used by the Stripe SDK. All icons are 32 x 20 points."}],"url":"\/documentation\/stripepaymentsui\/stpimagelibrary","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary","kind":"symbol","navigatorTitle":[{"text":"STPImageLibrary","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"STPImageLibrary"}],"title":"STPImageLibrary","type":"topic"},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI":{"type":"topic","title":"StripePaymentsUI","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI","kind":"symbol","role":"collection","url":"\/documentation\/stripepaymentsui","abstract":[{"type":"text","text":"The StripePaymentsUI module contains UI elements and API bindings for building a custom payment flow using Stripe."}]},"doc://com.stripe.stripe-payments-ui/documentation/StripePaymentsUI/STPImageLibrary/mastercardCardImage()":{"role":"symbol","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"mastercardCardImage","kind":"identifier"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"}],"type":"topic","identifier":"doc:\/\/com.stripe.stripe-payments-ui\/documentation\/StripePaymentsUI\/STPImageLibrary\/mastercardCardImage()","title":"mastercardCardImage()","navigatorTitle":[{"kind":"identifier","text":"mastercardCardImage"}],"url":"\/documentation\/stripepaymentsui\/stpimagelibrary\/mastercardcardimage()","abstract":[{"text":"An icon representing Mastercard.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"path":"\/metadata\/title","op":"replace","value":"mastercardCardImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"+ ","kind":"text"},{"text":"mastercardCardImage","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"mastercardCardImage","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":"STPImageLibrary","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/title"},{"value":[{"kind":"identifier","text":"STPImageLibrary"}],"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary\/navigatorTitle","value":[{"kind":"identifier","text":"STPImageLibrary"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1mastercardCardImage()\/title","op":"replace","value":"mastercardCardImage"},{"value":[{"text":"+ ","kind":"text"},{"text":"mastercardCardImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments-ui~1documentation~1StripePaymentsUI~1STPImageLibrary~1mastercardCardImage()\/fragments"}]}]}
