{"abstract":[{"type":"text","text":"The funding source for the card (credit, debit, prepaid, or other)"}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard"]]},"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"funding","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","text":"STPCardFundingType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"},{"text":" { get }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcard\/funding"]},{"paths":["\/documentation\/stripepayments\/stpcard\/funding"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"role":"symbol","title":"funding","externalID":"c:@M@StripePayments@objc(cs)STPCard(py)funding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"funding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","text":"STPCardFundingType"}],"symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"funding"}],"roleHeading":"Instance Property","modules":[{"name":"StripePayments"}]},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard":{"url":"\/documentation\/stripepayments\/stpcard","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard","kind":"symbol","abstract":[{"text":"Representation of a user’s credit card details that have been tokenized with","type":"text"},{"type":"text","text":" "},{"type":"text","text":"the Stripe API"}],"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"STPCard","kind":"identifier"}],"title":"STPCard","navigatorTitle":[{"text":"STPCard","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCard/funding":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCard\/funding","abstract":[{"type":"text","text":"The funding source for the card (credit, debit, prepaid, or other)"}],"kind":"symbol","url":"\/documentation\/stripepayments\/stpcard\/funding","type":"topic","role":"symbol","title":"funding","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"funding"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType","text":"STPCardFundingType"}],"navigatorTitle":[{"kind":"identifier","text":"funding"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCardFundingType":{"kind":"symbol","title":"STPCardFundingType","navigatorTitle":[{"text":"STPCardFundingType","kind":"identifier"}],"abstract":[{"type":"text","text":"The various funding sources for a payment card."}],"url":"\/documentation\/stripepayments\/stpcardfundingtype","type":"topic","role":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPCardFundingType","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"funding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"funding"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCardFundingType","text":"STPCardFundingType","kind":"typeIdentifier","preciseIdentifier":"c:@M@StripePayments@E@STPCardFundingType"},{"text":" ","kind":"text"},{"text":"funding","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/title","value":"STPCard"},{"value":[{"text":"STPCard","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard\/navigatorTitle","op":"replace","value":[{"text":"STPCard","kind":"identifier"}]},{"value":"funding","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1funding\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCard~1funding\/fragments","op":"replace","value":[{"kind":"identifier","text":"funding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/title","value":"STPCardFundingType"},{"value":[{"kind":"identifier","text":"STPCardFundingType"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/fragments"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCardFundingType\/navigatorTitle","value":[{"kind":"identifier","text":"STPCardFundingType"}],"op":"replace"}]}]}
