{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":"(presentApplePayOnViewController:completion:) ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"presentApplePay"},{"text":"(","kind":"text"},{"text":"on","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"viewController","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"STPVoidBlock","identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka"},{"kind":"text","text":"? = nil)"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"text":"The UIViewController instance to present the Apple Pay sheet on","type":"text"}]}]},{"name":"completion","content":[{"inlineContent":[{"type":"text","text":"Called after the Apple Pay sheet is presented"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"This method should only be called once; create a new instance of STPApplePayContext every time you present Apple Pay.","type":"text"}]}],"type":"aside"}]}],"metadata":{"role":"symbol","modules":[{"name":"StripeApplePay"}],"platforms":[],"externalID":"c:@M@StripeApplePay@objc(cs)STPApplePayContext(im)presentApplePayOnViewController:completion:","navigatorTitle":[{"kind":"identifier","text":"presentApplePayOnViewController:completion:"}],"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"presentApplePay","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"on"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIViewController","kind":"typeIdentifier","text":"UIViewController"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka","text":"STPVoidBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"symbolKind":"method","title":"presentApplePay(on:completion:)"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext"]]},"abstract":[{"text":"Presents the Apple Pay sheet from the specified view controller, starting the payment process.","type":"text"}],"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"Use `presentApplePay(completion:)` instead.","type":"text"}]}],"variants":[{"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(on:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(on:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"url":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(on:completion:)","interfaceLanguage":"swift"},"references":{"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay","abstract":[{"type":"text","text":"StripeApplePay is a lightweight Apple Pay SDK intended for building App Clips or other size-constrained apps."}],"url":"\/documentation\/stripeapplepay","role":"collection","kind":"symbol","type":"topic","title":"StripeApplePay"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext","role":"symbol","url":"\/documentation\/stripeapplepay\/stpapplepaycontext","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"STPApplePayContext","kind":"identifier"}],"abstract":[{"type":"text","text":"A helper class that implements Apple Pay."},{"text":" ","type":"text"},{"type":"text","text":"Usage looks like this:"}],"navigatorTitle":[{"kind":"identifier","text":"STPApplePayContext"}],"title":"STPApplePayContext"},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPApplePayContext/presentApplePay(on:completion:)":{"deprecated":false,"url":"\/documentation\/stripeapplepay\/stpapplepaycontext\/presentapplepay(on:completion:)","abstract":[{"text":"Presents the Apple Pay sheet from the specified view controller, starting the payment process.","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPApplePayContext\/presentApplePay(on:completion:)","type":"topic","navigatorTitle":[{"text":"presentApplePayOnViewController:completion:","kind":"identifier"}],"role":"symbol","kind":"symbol","title":"presentApplePay(on:completion:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"presentApplePay","kind":"identifier"},{"kind":"text","text":"("},{"text":"on","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UIViewController","preciseIdentifier":"c:objc(cs)UIViewController"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"STPVoidBlock","preciseIdentifier":"s:14StripeApplePay12STPVoidBlocka"},{"text":"?)","kind":"text"}]},"doc://com.stripe.stripe-apple-pay/documentation/StripeApplePay/STPVoidBlock":{"identifier":"doc:\/\/com.stripe.stripe-apple-pay\/documentation\/StripeApplePay\/STPVoidBlock","navigatorTitle":[{"kind":"identifier","text":"STPVoidBlock"}],"abstract":[{"text":"An empty block, called with no arguments, returning nothing.","type":"text"}],"type":"topic","kind":"symbol","title":"STPVoidBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"STPVoidBlock","kind":"identifier"}],"role":"symbol","url":"\/documentation\/stripeapplepay\/stpvoidblock"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/platforms","value":[],"op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"presentApplePayOnViewController:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"presentApplePayOnViewController:completion:"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"presentApplePayOnViewController:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIViewController","text":"UIViewController","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"viewController","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":" (^","kind":"text"},{"kind":"text","text":")()) "},{"kind":"internalParam","text":"completion"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"name":"viewController","content":[{"type":"paragraph","inlineContent":[{"text":"The UIViewController instance to present the Apple Pay sheet on","type":"text"}]}]},{"name":"completion","content":[{"type":"paragraph","inlineContent":[{"text":"Called after the Apple Pay sheet is presented","type":"text"}]}]}]},"path":"\/primaryContentSections\/1","op":"replace"},{"value":"STPApplePayContext","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/fragments","value":[{"text":"STPApplePayContext","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext\/navigatorTitle","op":"replace","value":[{"text":"STPApplePayContext","kind":"identifier"}]},{"value":"presentApplePayOnViewController:completion:","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(on:completion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-apple-pay~1documentation~1StripeApplePay~1STPApplePayContext~1presentApplePay(on:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"presentApplePayOnViewController:completion:","kind":"identifier"}]}]}]}
