{"identifier":{"url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/invalidClientSecret","interfaceLanguage":"swift"},"metadata":{"externalID":"c:@M@StripePayments@E@STPCollectBankAccountError@STPCollectBankAccountErrorInvalidClientSecret","modules":[{"name":"StripePayments"}],"navigatorTitle":[{"text":"STPCollectBankAccountErrorInvalidClientSecret","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidClientSecret"}],"roleHeading":"Case","title":"STPCollectBankAccountError.invalidClientSecret","symbolKind":"case","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/stripepayments\/stpcollectbankaccounterror\/invalidclientsecret"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/stripepayments\/stpcollectbankaccounterror\/invalidclientsecret"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Error when a secret can not be parsed to retrieve the ID","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":"(STPCollectBankAccountErrorInvalidClientSecret) "},{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidClientSecret","kind":"identifier"}],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError/invalidClientSecret":{"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError\/invalidClientSecret","title":"STPCollectBankAccountError.invalidClientSecret","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror\/invalidclientsecret","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidClientSecret"}],"abstract":[{"type":"text","text":"Error when a secret can not be parsed to retrieve the ID"}],"role":"symbol","navigatorTitle":[{"text":"STPCollectBankAccountErrorInvalidClientSecret","kind":"identifier"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPCollectBankAccountError":{"abstract":[{"text":"Error codes generated by STPBankAccountCollector","type":"text"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPCollectBankAccountError","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"STPCollectBankAccountError","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"STPCollectBankAccountError","kind":"identifier"}],"title":"STPCollectBankAccountError","url":"\/documentation\/stripepayments\/stpcollectbankaccounterror","type":"topic"},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"STPCollectBankAccountErrorInvalidClientSecret","op":"replace"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"STPCollectBankAccountErrorInvalidClientSecret"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"STPCollectBankAccountErrorInvalidClientSecret","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"value":"STPCollectBankAccountErrorInvalidClientSecret","op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1invalidClientSecret\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError~1invalidClientSecret\/fragments","value":[{"kind":"identifier","text":"STPCollectBankAccountErrorInvalidClientSecret"}]},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/title","value":"STPCollectBankAccountError"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/fragments","value":[{"kind":"identifier","text":"STPCollectBankAccountError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPCollectBankAccountError\/navigatorTitle","value":[{"text":"STPCollectBankAccountError","kind":"identifier"}],"op":"replace"}]}]}
