{"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Alliance Bank"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand"]]},"variants":[{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/alliancebank"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/stripepayments\/stpfpxbankbrand\/alliancebank"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"allianceBank","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/allianceBank"},"metadata":{"roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrandAllianceBank"}],"externalID":"c:@M@StripePayments@E@STPFPXBankBrand@STPFPXBankBrandAllianceBank","symbolKind":"case","modules":[{"name":"StripePayments"}],"title":"STPFPXBankBrand.allianceBank","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"allianceBank","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand/allianceBank":{"abstract":[{"type":"text","text":"Alliance Bank"}],"type":"topic","url":"\/documentation\/stripepayments\/stpfpxbankbrand\/alliancebank","navigatorTitle":[{"text":"STPFPXBankBrandAllianceBank","kind":"identifier"}],"title":"STPFPXBankBrand.allianceBank","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"allianceBank","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand\/allianceBank"},"doc://com.stripe.stripe-payments/documentation/StripePayments/STPFPXBankBrand":{"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"STPFPXBankBrand"}],"identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments\/STPFPXBankBrand","title":"STPFPXBankBrand","url":"\/documentation\/stripepayments\/stpfpxbankbrand","abstract":[{"type":"text","text":"The various bank brands available for FPX payments."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"STPFPXBankBrand"}]},"doc://com.stripe.stripe-payments/documentation/StripePayments":{"title":"StripePayments","role":"collection","url":"\/documentation\/stripepayments","type":"topic","kind":"symbol","identifier":"doc:\/\/com.stripe.stripe-payments\/documentation\/StripePayments","abstract":[{"text":"The StripePayments module contains bindings for the Stripe Payments API.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"STPFPXBankBrandAllianceBank"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrandAllianceBank"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"STPFPXBankBrandAllianceBank","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0"},{"value":"STPFPXBankBrandAllianceBank","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1allianceBank\/title","op":"replace"},{"value":[{"kind":"identifier","text":"STPFPXBankBrandAllianceBank"}],"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand~1allianceBank\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/title","value":"STPFPXBankBrand"},{"path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/fragments","value":[{"kind":"identifier","text":"STPFPXBankBrand"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.stripe.stripe-payments~1documentation~1StripePayments~1STPFPXBankBrand\/navigatorTitle","value":[{"kind":"identifier","text":"STPFPXBankBrand"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}
